name: Build Kivy APK

on:
  push:
    branches:
      - main  # This triggers the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools git
        pip install buildozer

    - name: Build APK
      run: |
        cd ${{ github.workspace }}  # Navigate to the root of the repository
        buildozer android debug  # This will build the APK

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: myapp-apk
        path: bin/*.apk  # The APK is generated in the 'bin' directory within the repo root
