name: Build Kivy APK

on:
  push:
    branches:
      - main  # This triggers the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      run: |
        sudo apt-get install -y openjdk-11-jdk  # Install OpenJDK 11

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools git cython3  # Install necessary packages
        pip install buildozer

    - name: Install Android SDK Command-line Tools
      run: |
        sudo apt-get install -y android-sdk  # Install Android SDK
        sudo apt-get install -y android-sdk-commandlinetools  # Install command-line tools
        echo "export ANDROID_HOME=/usr/lib/android-sdk" >> $GITHUB_ENV  # Set ANDROID_HOME environment variable
        echo "export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_ENV  # Add cmdline-tools to PATH
        yes | sdkmanager --licenses  # Automatically accept all licenses
        sdkmanager "build-tools;36.0.0"  # Specify the build-tools version you want

    - name: Build APK
      run: |
        cd ${{ github.workspace }}  # Navigate to the root of the repository
        buildozer android debug  # This will build the APK

    - name: Upload APK
      uses: actions/upload-artifact@v3  # Update to v3
      with:
        name: myapp-apk
        path: bin/*.apk  # The APK is generated in the 'bin' directory within the repo root
