name: Run LigueMagnus Rankings Script

on:
  # schedule:
  #   - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-rankings-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - name: Run Rankings script
      run: python LigueMagnus_Rankings_Selenium.py
    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add ligue_magnus_rankings.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update rankings CSV file" && git push)

